from .userCreateView import UserCreateView
from .userDetailView import UserDetailView
from .categoriaView import CategoriaView
from .categoriaDetailView import CategoriaDetailView
from .productoView import ProductoView
from .productoDetailView import ProductoDetailView
from .modeloDetailView import ModeloDetailView
from .modeloView import ModeloView
from .clientesView import ClientesView
from .clientesDetailView import ClientesDetailView
