# Generated by Django 4.1.1 on 2022-09-22 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Articulo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Celular', models.CharField(max_length=10)),
                ('Correo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=45)),
                ('Categoria_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Dulces_sueños.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Talla', models.CharField(max_length=10)),
                ('Modelo_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Dulces_sueños.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Clientes_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Dulces_sueños.clientes')),
                ('Producto_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Dulces_sueños.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('Venta_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Dulces_sueños.venta')),
            ],
        ),
    ]
