# Generated by Django 4.1.1 on 2022-09-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Dulces_sueños', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='Cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='Valor_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='Precio_Mayor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='Precio_Unidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='Stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='Cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='Valor_total',
            field=models.IntegerField(null=True),
        ),
    ]
