# Generated by Django 4.1.1 on 2022-09-30 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Dulces_sueños', '0002_factura_cantidad_factura_valor_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='Articulo',
            field=models.CharField(max_length=20, verbose_name='Articulo'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Celular',
            field=models.CharField(max_length=10, verbose_name='Numero de celular'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Correo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Cantidad',
            field=models.IntegerField(null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Valor_total',
            field=models.IntegerField(null=True, verbose_name='Valor total a pagar'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='Categoria_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Dulces_sueños.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='Descripcion',
            field=models.CharField(max_length=45, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Precio_Mayor',
            field=models.IntegerField(null=True, verbose_name='Precio X Mayor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Precio_Unidad',
            field=models.IntegerField(null=True, verbose_name='Precio X Unidad'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Stock',
            field=models.IntegerField(null=True, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Talla',
            field=models.CharField(choices=[('20', 'Talla 20'), ('22', 'Talla 22'), ('24', 'Talla 24'), ('26', 'Talla 26'), ('28', 'Talla 28'), ('30', 'Talla 30'), ('32', 'Talla 32'), ('34', 'Talla 34'), ('36', 'Talla 36'), ('38', 'Talla 38'), ('40', 'Talla 40'), ('42', 'Talla 42'), ('44', 'Talla 44')], max_length=2, verbose_name='Talla'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='Cantidad',
            field=models.IntegerField(null=True, verbose_name='Cantidad de productos'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='Valor_total',
            field=models.IntegerField(null=True, verbose_name='Valor total de venta'),
        ),
    ]
